// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

Texture2D<float4> Input;

RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    Result[id.xy].rgb = (Input[id.xy].r / 2, clamp(Input[id.xy].g * 2, 0, 1), Input[id.xy].b / 2);

}
